# Generated by Django 5.2.1 on 2025-06-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_alt',
            field=models.CharField(default='No alt text provided', max_length=255),
        ),
    ]
